/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.forms;

import javax.servlet.http.HttpServletRequest;
import org.apache.struts.action.ActionErrors;
import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionMapping;
import com.entity.UserType;

/** 
 * MyEclipse Struts
 * Creation date: 04-07-2016
 * 
 * XDoclet definition:
 * @struts.form name="userTypeForm"
 */
public class UserTypeForm extends ActionForm {
	/*
	 * Generated fields
	 */

	/** item property */
	private UserType item;

	/*
	 * Generated Methods
	 */

	/** 
	 * Method validate
	 * @param mapping
	 * @param request
	 * @return ActionErrors
	 */
	public ActionErrors validate(ActionMapping mapping,
			HttpServletRequest request) {
		// TODO Auto-generated method stub
		return null;
	}

	/** 
	 * Method reset
	 * @param mapping
	 * @param request
	 */
	public void reset(ActionMapping mapping, HttpServletRequest request) {
		// TODO Auto-generated method stub
	}

	/** 
	 * Returns the item.
	 * @return UserType
	 */
	public UserType getItem() {
		return item;
	}

	/** 
	 * Set the item.
	 * @param item The item to set
	 */
	public void setItem(UserType item) {
		this.item = item;
	}
}