/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.actions;

import java.util.List;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dao.IUsersDAO;
import com.entity.Users;
import com.struts.forms.UsersForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-08-2016
 * 
 * XDoclet definition:
 * @struts.action path="/users" name="usersForm" parameter="operate" scope="request" validate="true"
 */
public class UsersAction extends DispatchAction {
	IUsersDAO iUsersDAO;
	public void setiUsersDAO(IUsersDAO iUsersDAO) {
		this.iUsersDAO = iUsersDAO;
	}

	public ActionForward doLogin(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UsersForm usersForm = (UsersForm) form;
		String result = "failure";
		List list = iUsersDAO.selectByCondition(usersForm.getItem());
		if(null!=list && list.size()>0){
			HttpSession session = request.getSession();
			session.setAttribute("USER", list.get(0));
			result = "success";
		}else{
			result = "failure";
		}
		return mapping.findForward(result);
	}
	public ActionForward doExit(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		HttpSession session = request.getSession();
		session.removeAttribute("USER");
		return mapping.findForward("success");
	}
	
}