/*
 * Generated by MyEclipse Struts
 * Template path: templates/java/JavaClass.vtl
 */
package com.struts.actions;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

import org.apache.struts.action.ActionForm;
import org.apache.struts.action.ActionForward;
import org.apache.struts.action.ActionMapping;
import org.apache.struts.actions.DispatchAction;

import com.dao.IUserTypeDAO;
import com.struts.forms.UserTypeForm;

/** 
 * MyEclipse Struts
 * Creation date: 04-07-2016
 * 
 * XDoclet definition:
 * @struts.action path="/userType" name="userTypeForm" scope="request" validate="true"
 */
public class UserTypeAction extends DispatchAction {
	IUserTypeDAO iUserTypeDAO;
	
	public void setiUserTypeDAO(IUserTypeDAO iUserTypeDAO) {
		this.iUserTypeDAO = iUserTypeDAO;
	}

	public ActionForward execute(ActionMapping mapping, ActionForm form,
			HttpServletRequest request, HttpServletResponse response) {
		UserTypeForm userTypeForm = (UserTypeForm) form;// TODO Auto-generated method stub
		return null;
	}
}